import "./globals.css";
import Footer from 'src/components/footer/Footer'
import TopBar from 'src/components/navbar/TopBar'
import DropMenu from 'src/components/navbar/DropMenu'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body> 
          <DropMenu />
          <TopBar />
          {children}
          <Footer /> 
        </body>
    </html>
  )
}
